version: "3.8"

services:
  web:
    image: backend:latest
    build:
      context: .
      args:
        # Unfortunately, docker-compose does not somehow support using container's .envs
        # This will pass DEBUG argument from host's environment ("make up" loads django.env before composing)
        - DEBUG=${DEBUG}
    ports:
      - "80:8000"
    env_file:
      - .envs/prod/django.env
      - .envs/prod/aws.env
    depends_on:
      - db

  db:
    restart: unless-stopped
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/prod/postgres.env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
