version: "3.8"

services:
  web:
    image: backend:latest
    build: .
    ports:
      - "80:8000"
    env_file:
      - .envs/dev/django.env
      - .envs/dev/aws.env
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
    - postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/dev/postgres.env
    ports:
    - "8001:5432"

volumes:
  postgres_data: